# Generated by Django 4.1 on 2024-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTIH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(choices=[('base_start', 249), ('top_start', 349), ('base_end', 349), ('top_end', 499)], default='base')),
                ('tier', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=63)),
                ('fullname', models.CharField(max_length=63)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=31)),
                ('order_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
