# Generated by Django 4.1 on 2024-07-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertih',
            name='tier',
        ),
        migrations.AlterField(
            model_name='ordertih',
            name='price',
            field=models.IntegerField(choices=[('tih_start', '690'), ('tih_end', '890')], default='tih_end'),
        ),
    ]
