# Generated by Django 4.1 on 2024-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.IntegerField(
                        choices=[("base", "499"), ("top", "999")], default="base"
                    ),
                ),
                ("tier", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255)),
                ("fullname", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
    ]
