# Generated by Django 4.1 on 2024-02-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benefit", "0002_order_payment_status_alter_order_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="some id ofr this speciciddpldld", max_length=255
            ),
            preserve_default=False,
        ),
    ]
