# Generated by Django 4.1 on 2024-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benefit", "0004_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(
                choices=[("base", "249"), ("top", "349")], default="base"
            ),
        ),
    ]
