# Generated by Django 4.1 on 2024-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benefit", "0005_alter_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="signature",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(
                choices=[
                    ("base_start", "249"),
                    ("top_start", "349"),
                    ("base_end", "349"),
                    ("top_end", "499"),
                ],
                default="base",
            ),
        ),
    ]
