# Generated by Django 4.1 on 2024-07-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(choices=[('base_start', '249'), ('top_start', '449'), ('base_end', '349'), ('top_end', '549')], default='base'),
        ),
    ]
